version: '3.8'
services:
  mysql:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - mysql
    ports:
      - "5000:5000"

volumes:
  mysql_data:
  app_data:
